; Listing generated by Microsoft (R) Optimizing Compiler Version 19.12.25834.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\298th\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.cpp"
